name: crowdsense
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.9.0
  - ipykernel

  - pip:
      - flask==3.0.3
      - opencv-python==4.10.0.84
      - ultralytics==8.4.14
      - joblib==1.4.2
      - pillow==10.3.0
